apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller-manager
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: {{ include "odoo-operator.fullname" . }}-controller-manager
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: manager
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}