apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "odoo-operator.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
rules:
# 1. Permissões para o nosso Custom Resource (OdooInstance)
- apiGroups:
  - odoo.cloud104.io
  resources:
  - odooinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - odoo.cloud104.io
  resources:
  - odooinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - odoo.cloud104.io
  resources:
  - odooinstances/finalizers
  verbs:
  - update

# 2. Permissões para os Workloads do Kubernetes
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# 3. Permissões para Rede e Armazenamento (Core)
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# 4. Permissoes para o Cert-Manager
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# 5. Permissoes para Leader Election e Eventos do Kubernetes
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

# 6. Permissoes para o OdooDatabase (CRD secundario)
- apiGroups:
  - odoo.cloud104.io
  resources:
  - odoodatabases
  - odoodatabases/status
  - odoodatabases/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# 7. Permissoes para os Workloads do Banco de Dados (Jobs)
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# 8. Permissoes para Rede antiga (Ingress)
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "odoo-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "odoo-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "odoo-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}