apiVersion: odoo.cloud104.io/v1alpha1
kind: OdooInstance
metadata:
  labels:
    app.kubernetes.io/name: odooinstance
    app.kubernetes.io/managed-by: kustomize
  name: meu-erp
spec:
  domain: erp.local
  odoo:
    image: odoo:17.0
    replicas: 1
    storageSize: 2Gi
  database:
    image: postgres:16
    user: odoo
    storageSize: 2Gi