apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: odoo.totvs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: meu-erp-app # Substitua pelo nome exato do seu Service
            port:
              number: 8069