apiVersion: odoo.cloud104.io/v1alpha1
kind: OdooDatabase
metadata:
  labels:
    app.kubernetes.io/name: odoo-operator
    app.kubernetes.io/managed-by: kustomize
  name: odoodatabase-sample
spec:
  # TODO(user): Add fields here
