apiVersion: odoo.cloud104.io/v1alpha1
kind: OdooDatabase
metadata:
  labels:
    app.kubernetes.io/name: odoodatabase
    app.kubernetes.io/managed-by: kustomize
  name: cliente-acme
spec:
  instanceRef:
    name: meu-erp
  dbName: acme
  domain: acme.erp.local
  lang: pt_BR
  demoData: true